---
title: "Warwick's Progress: 1000 Km in May 2021"

date: "May 6, 2021"

output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gganimate)
```

```{r load_data, echo=FALSE, message=FALSE}
date_cumulativekm <- read_csv("data/date_cumulativekm.csv")
```

```{r prep_data, echo=FALSE, message=FALSE}
date_cumulativekm_dailykm <- date_cumulativekm %>%
  mutate(DAILY_KM = ifelse(is.na(lag(CUMULATIVE_KM)), 0, CUMULATIVE_KM - lag(CUMULATIVE_KM))) 
```

```{r graph01, echo=FALSE, warning=FALSE}
#animate <- ggplot(data = date_cumulativekm_dailykm, aes(x = DAY, y = CUMULATIVE_KM)) +
#           geom_line() +
#           geom_vline(xintercept = 31, linetype = "dashed") +
#           geom_hline(yintercept = 1000, linetype = "dashed") +
#           xlim(0, 31) +
#           ylim(0, 1000) +
#           labs(title = "Daily and Cumulative Km by Challenge Day", x = "Challenge Day", y = "KM") +
#           geom_col(width = 0.2, aes(x = DAY, y = DAILY_KM)) +
#           transition_time(DAY) 
#animate(animate, renderer=gifski_renderer(), nframes = 30, duration = 20, fps = 20, end_pause = 60, rewind = FALSE)


animate <- ggplot(data = date_cumulativekm_dailykm, aes(x = DAY, y = CUMULATIVE_KM)) +
  geom_line() +
  geom_vline(xintercept = 31, linetype = "dashed") +
  geom_hline(yintercept = 1000, linetype = "dashed") +
  xlim(0, 31) +
  ylim(0, 1000) +
  labs(title = "Daily and Cumulative Km by Challenge Day", x = "Challenge Day", y = "KM") +
  transition_reveal(DAY) +
  geom_col(width = 0.2, aes(group=seq_along(DAY), y = DAILY_KM))

animate(animate, renderer=gifski_renderer(), nframes = 10, duration = 10, fps = 10, end_pause = 60, rewind = FALSE)
```
